### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by sbhadr** [Jeamz/Artificial-Intelligence#1]
I could have a use for this with Iris. Interesting concept. 

Did you make this or was it copied?

**Comment by Jeamz** [comment]
Right now it consists of just basic classifying algorithms, but everyday I'll keep slowly expanding it to more advanced stuff. What kind of use would you have for it? Also the algorithms are well known in machine learning, All I did was recreate them from scratch and then compare them against the sklearn library.

**Comment by sbhadr** [comment]
I'm considering allowing support for Machine Learning in Iris's standard library. This way the language could be much more diverse and useful for developers not to mention for personal use. Seen as you have the skill to do it, I rather you help me directly with Iris as a core developer. That's if you're up to it. 

Python is easy to learn. Have a reference near you at all times and don't hesitate to find answers. Repetition is key to programming.  

Impressed with this.

**Comment by Jeamz** [comment]
Right now, I'm in the learning stages of Machine Learning, and this repo serves to provide simple examples of machine learning algorithms and help me as well as others learning it. I'll be happy to contribute to Iris, but note that I'm just starting out with machine learning and the algorithms here are rudimentary, If you think these algorithms will be applied to large/complex data they will need to be scaled up for efficiency. As time progresses and I get more familiar with this field, I will improve this repo.

**Comment by sbhadr** [comment]
I dissolved the "Leave once, you're gone" rule to help bring about a positive attitude towards the company as a whole. Unfortunately, Iris is under Sage Technologies as it's considered a project of R&D. To allow you to become a core developer, you will need to be rehired as a full stack developer. 

In your absence, I learned a few things of my own. In order for this company to be success or moderately self-sufficient, we have to work as a team. The company is more or less a house; figuratively speaking. We were it's foundation. You can't hold a house on sand. It has to be a solid, firm material. 

Another thing, we lacked proper clarity. More so myself. Mark put the assumption that we'd be making millions at the age of 16 and frankly, I didn't realize the amount of work that this would be. Going in, I genuinely thought that a single app would bring us above everyone else. Truthfully, it doesn't. In order to be successful, you have to be realistic. A company takes patience, teamwork and creativity. I lacked all three. 

My mistakes as being the CEO of this company has lead us to go into decline. I wasn't thinking about the moment but rather future. I have myself to blame and I take full responsibility. 

No one teaches you how to create a company, how to hire the right people or how to believe in what you want accomplished. The company is an extension of yourself. It's your ideas; philosophy. Truth is, I want this company to still be here when I finish college so I have a job.

**Comment by sbhadr** [comment]
Iris has been on my mind for a while. The first versions of it was Nutty. Nutty was a project that I worked on over the summer of 2015. The rewrite of Nutty is Iris. However, I had more in mind this time. 

Iris was supposed to be purely front-end development as a viable alternative to C++. Though, I still want that functionality, I decided to "open a door" and made it general-purpose. However, after looking at this, I think that this will allow easier creation of AI solutions or better machine learning practices. 

Our generation needs to know more about AI than ever before and I think this could be a viable solution.

**Comment by Jeamz** [comment]
I'm glad to hear this. I think your right about company acting as a house, if this is going to work we need to function as a team, and a team is only as strong as it's weakest player. You were right about me not taking full action of my board position, from now on I'll be working on the company and projects more. I'll rejoin the company but understand that I will have times where I need to focus on school more and thus not working on the company. I'm going to work on the company as much as I can (definitely more than I have been the past few months) but don't expect full time.

**Comment by Jeamz** [comment]
Over the next week or so, I was planning to continue learning and populating this repo. Then if ready, starting a personal project to apply these Machine Learning ideas. Also, over the last few weeks, The 'Milton Computer Science Society' has been growing and expanding, therefore If I rejoin the company, I can incorporate that as a incubator for projects/ideas/people.

**Comment by sbhadr** [comment]
I'm glad that we both learned from this. I'll be putting in equal effort to this company. However, I understand that you will need some time for school as will I. Iris is due on the 24th of this current month. As such, will be our first product. 

In conjunction to AL solutions, I would love to have a dedicated math library as part of the Standard Library. Seen as you're both passionate about it and the best at it, I think it would be wise if you authored and maintained it. 

This repo could quite possibly turn into a library in the Standard Library of Iris. But before you consider it, please consider this. I have a lot of repos that I work on and maintain. Creating an open-sourced library is great but you have to update, maintain and fix all its problems or problems that arise. 

Another thing, I can tell that you're passionate about AI solutions. Passion is what drives people to success. Don't let it go. It's traffic and you're in the middle. 

Rejoining the company is up to you. I restricted most departments from operating until a product is released. Felt like a waste to have people do nothing; marketing in particular. As such, you're welcome to join back. I'm not sure if I can give your former status back to you.

**Comment by Jeamz** [comment]
Great, consider me rejoined. I'll continue building up this repo as planned and as for a general math library, I'll be contributing that directly to the iris repo.

**Comment by sbhadr** [comment]
Sent an invite to allow you to edit the repo. Check the issues tab on Iris.
